// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OscarBot.Classes;

namespace OscarBot.Migrations
{
    [DbContext(typeof(EntityContext))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("OscarBot.Classes.ApiKey", b =>
                {
                    b.Property<string>("Service")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.HasKey("Service");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("OscarBot.Classes.ModerationAction", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("ModeratorId");

                    b.Property<string>("Reason");

                    b.Property<DateTime>("ReverseAfter");

                    b.Property<DateTime>("Timestamp");

                    b.Property<int>("Type");

                    b.HasKey("UserId");

                    b.HasIndex("GuildId");

                    b.ToTable("ModerationAction");
                });

            modelBuilder.Entity("OscarBot.Classes.ModerationActionCollection", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("GuildId");

                    b.ToTable("ModerationActions");
                });

            modelBuilder.Entity("OscarBot.Classes.Prefix", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GuildPrefix");

                    b.HasKey("Id");

                    b.ToTable("Prefixes");
                });

            modelBuilder.Entity("OscarBot.Classes.ModerationAction", b =>
                {
                    b.HasOne("OscarBot.Classes.ModerationActionCollection")
                        .WithMany("Actions")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
